Algoritmo "semnome"
//Calcule e apresente a área de um triângulo: Área = (base * altura) / 2
Var

   base: real
   altura: real
   area: real

Inicio

   //área de um triângulo
   escreval("Digite o tamanho da base do triângulo")
   leia(base)
   escreval("Digite o tamanho da altura do triângulo")
   leia(altura)
   area <- (base * altura/2)
   escreval("A área do triângulo é de",area)

Fimalgoritmo