Algoritmo "semnome"
//Leia duas variáveis numéricas e apresente a soma entre elas, podendo ou não armazenar o resultado em uma
//terceira variável.
Var
   valor1:real
   valor2:real
   soma: real

Inicio

   escreval("Digite o primeiro valor")
   leia(valor1)
   escreval("Digite o segundo valor")
   leia(valor2)

   soma <- valor1 + valor2

   escreval("O resultado da soma é", soma)


Fimalgoritmo