Algoritmo "semnome"
//Leia 3 números inteiros e calcule a multiplicação entre eles.
Var

  n1:inteiro
  n2:inteiro
  n3:inteiro
  multi:inteiro

Inicio

   escreval("Informe o primeiro número")
   leia(n1)
   escreval("Informe o segundo número")
   leia(n2)
   escreval("Informe o terceiro número")
   leia(n3)
   
   multi <- n1*n2*n3

   escreval("A multiplicação dos números é:",multi)

Fimalgoritmo