Algoritmo "semnome"
//Leia 3 números e calcule: (primeiro número + terceiro número) * segundo número
Var

  n1:real
  n2:real
  n3:real
  resul:real

Inicio

   escreval("Informe o primeiro número")
   leia(n1)
   escreval("Informe o segundo número")
   leia(n2)
   escreval("Informe o terceiro número")
   leia(n3)
   
   resul <- (n1+n3)*n2

   escreval("O resultado da soma do primeiro e do terceiro número vezes o segundo número é de:",resul)

Fimalgoritmo